version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 00834bed53473ce3412fa40137ddaacd839464b4d5ce346196a72af240db3f45
    docker:
      - image: node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Setup Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            ./tmp/cc-test-reporter before-build
      - run: npm run lint
      - run:
          name: Test coverage
          command: |
            npm run test:coverage
            ./tmp/cc-test-reporter after-build -t lcov
